repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.4.1
    hooks:
      - id: nbqa-black
        args: [--nbqa-mutate]
        additional_dependencies: [black==20.8b1]

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
        exclude: components-mnist/mnist-train/tests/datasets
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-xml
      - id: check-json
        exclude: .vscode
      - id: check-ast
      - id: name-tests-test
        exclude: components-mnist/mnist-train/tests/helpers

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: circleci-config-validate
      - id: forbid-binary
        exclude: components-mnist/mnist-train/tests/datasets
      - id: shellcheck

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        # language_version: python3.9

  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
      - id: nbstripout
        files: ".ipynb"

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        # language_version: python3.9
        language: system
